name: Login_App
publish_to: none

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
 
    
  uuid: ^3.0.7
  local_auth: ^2.1.2
  http: ^0.13.5
  provider: ^6.0.4
  retrofit: ^3.3.1
  logger: ^0.9.1
  dio: ^4.0.6
  json_annotation: ^4.7.0

dev_dependencies:
  # Used by tests. Not required to use `json_serializable`.
  build_runner: ^2.0.0
  retrofit_generator: ^4.2.0
  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^3.0.0

  json_serializable: ^6.0.0

  flutter_test: 
    sdk: flutter

  # Not required to use `json_serializable`.
  lints: ^2.0.0
  path: ^1.8.0
  test: ^1.16.0

